//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectx1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int id { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> room_id { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
