//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectx1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string username { get; set; }
        public string role { get; set; }
        public string password { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsFirstLogin { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
    }
}
